# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'clientes.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(402, 811)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.cb_seleccionar_cliente = QComboBox(self.centralwidget)
        self.cb_seleccionar_cliente.addItem("")
        self.cb_seleccionar_cliente.setObjectName(u"cb_seleccionar_cliente")
        self.cb_seleccionar_cliente.setGeometry(QRect(20, 30, 371, 22))
        self.label_txt_seleccione_cliente = QLabel(self.centralwidget)
        self.label_txt_seleccione_cliente.setObjectName(u"label_txt_seleccione_cliente")
        self.label_txt_seleccione_cliente.setGeometry(QRect(20, 10, 131, 16))
        self.label_txt_id = QLabel(self.centralwidget)
        self.label_txt_id.setObjectName(u"label_txt_id")
        self.label_txt_id.setGeometry(QRect(20, 90, 47, 13))
        self.label_id_cliente = QLabel(self.centralwidget)
        self.label_id_cliente.setObjectName(u"label_id_cliente")
        self.label_id_cliente.setGeometry(QRect(40, 86, 351, 20))
        self.label_id_cliente.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_txt_domicilio_alquiler = QLabel(self.centralwidget)
        self.label_txt_domicilio_alquiler.setObjectName(u"label_txt_domicilio_alquiler")
        self.label_txt_domicilio_alquiler.setGeometry(QRect(20, 110, 81, 16))
        self.label_txt_numero_telefono = QLabel(self.centralwidget)
        self.label_txt_numero_telefono.setObjectName(u"label_txt_numero_telefono")
        self.label_txt_numero_telefono.setGeometry(QRect(20, 130, 101, 16))
        self.label_txt_monto_alquiler = QLabel(self.centralwidget)
        self.label_txt_monto_alquiler.setObjectName(u"label_txt_monto_alquiler")
        self.label_txt_monto_alquiler.setGeometry(QRect(20, 150, 91, 16))
        self.label_txt_monto_deposito_numero = QLabel(self.centralwidget)
        self.label_txt_monto_deposito_numero.setObjectName(u"label_txt_monto_deposito_numero")
        self.label_txt_monto_deposito_numero.setGeometry(QRect(20, 170, 121, 20))
        self.label_txt_fecha_inicio_contrato = QLabel(self.centralwidget)
        self.label_txt_fecha_inicio_contrato.setObjectName(u"label_txt_fecha_inicio_contrato")
        self.label_txt_fecha_inicio_contrato.setGeometry(QRect(20, 190, 151, 16))
        self.label_txt_fecha_fin_contrato = QLabel(self.centralwidget)
        self.label_txt_fecha_fin_contrato.setObjectName(u"label_txt_fecha_fin_contrato")
        self.label_txt_fecha_fin_contrato.setGeometry(QRect(20, 210, 131, 16))
        self.label_txt_propietario = QLabel(self.centralwidget)
        self.label_txt_propietario.setObjectName(u"label_txt_propietario")
        self.label_txt_propietario.setGeometry(QRect(20, 230, 71, 16))
        self.label_txt_tipo_comision = QLabel(self.centralwidget)
        self.label_txt_tipo_comision.setObjectName(u"label_txt_tipo_comision")
        self.label_txt_tipo_comision.setGeometry(QRect(20, 250, 91, 16))
        self.label_txt_monto_comision = QLabel(self.centralwidget)
        self.label_txt_monto_comision.setObjectName(u"label_txt_monto_comision")
        self.label_txt_monto_comision.setGeometry(QRect(20, 270, 101, 16))
        self.label_txt_cuota_aguas_cordobesas = QLabel(self.centralwidget)
        self.label_txt_cuota_aguas_cordobesas.setObjectName(u"label_txt_cuota_aguas_cordobesas")
        self.label_txt_cuota_aguas_cordobesas.setGeometry(QRect(20, 290, 151, 16))
        self.label_txt_importe_aguas_cordobesas = QLabel(self.centralwidget)
        self.label_txt_importe_aguas_cordobesas.setObjectName(u"label_txt_importe_aguas_cordobesas")
        self.label_txt_importe_aguas_cordobesas.setGeometry(QRect(20, 310, 161, 16))
        self.label_txt_porcentual_aguas_cordobesas = QLabel(self.centralwidget)
        self.label_txt_porcentual_aguas_cordobesas.setObjectName(u"label_txt_porcentual_aguas_cordobesas")
        self.label_txt_porcentual_aguas_cordobesas.setGeometry(QRect(20, 330, 201, 16))
        self.label_txt_quien_paga_aguas = QLabel(self.centralwidget)
        self.label_txt_quien_paga_aguas.setObjectName(u"label_txt_quien_paga_aguas")
        self.label_txt_quien_paga_aguas.setGeometry(QRect(20, 350, 131, 16))
        self.label_txt_cuota_muni = QLabel(self.centralwidget)
        self.label_txt_cuota_muni.setObjectName(u"label_txt_cuota_muni")
        self.label_txt_cuota_muni.setGeometry(QRect(20, 370, 81, 16))
        self.label_txt_importe_muni = QLabel(self.centralwidget)
        self.label_txt_importe_muni.setObjectName(u"label_txt_importe_muni")
        self.label_txt_importe_muni.setGeometry(QRect(20, 390, 91, 16))
        self.label_txt_quien_paga_muni = QLabel(self.centralwidget)
        self.label_txt_quien_paga_muni.setObjectName(u"label_txt_quien_paga_muni")
        self.label_txt_quien_paga_muni.setGeometry(QRect(20, 410, 91, 16))
        self.label_txt_cuota_rentas = QLabel(self.centralwidget)
        self.label_txt_cuota_rentas.setObjectName(u"label_txt_cuota_rentas")
        self.label_txt_cuota_rentas.setGeometry(QRect(20, 430, 91, 16))
        self.label_txt_importe_rentas = QLabel(self.centralwidget)
        self.label_txt_importe_rentas.setObjectName(u"label_txt_importe_rentas")
        self.label_txt_importe_rentas.setGeometry(QRect(20, 450, 111, 16))
        self.label_txt_quien_paga_rentas = QLabel(self.centralwidget)
        self.label_txt_quien_paga_rentas.setObjectName(u"label_txt_quien_paga_rentas")
        self.label_txt_quien_paga_rentas.setGeometry(QRect(20, 470, 101, 16))
        self.label_txt_monto_unico = QLabel(self.centralwidget)
        self.label_txt_monto_unico.setObjectName(u"label_txt_monto_unico")
        self.label_txt_monto_unico.setGeometry(QRect(20, 490, 71, 16))
        self.label_txt_mes_expensa = QLabel(self.centralwidget)
        self.label_txt_mes_expensa.setObjectName(u"label_txt_mes_expensa")
        self.label_txt_mes_expensa.setGeometry(QRect(20, 510, 71, 16))
        self.label_txt_monto_expensa = QLabel(self.centralwidget)
        self.label_txt_monto_expensa.setObjectName(u"label_txt_monto_expensa")
        self.label_txt_monto_expensa.setGeometry(QRect(20, 530, 81, 16))
        self.label_txt_adicional_pagares = QLabel(self.centralwidget)
        self.label_txt_adicional_pagares.setObjectName(u"label_txt_adicional_pagares")
        self.label_txt_adicional_pagares.setGeometry(QRect(20, 550, 91, 16))
        self.label_txt_cuenta_orden = QLabel(self.centralwidget)
        self.label_txt_cuenta_orden.setObjectName(u"label_txt_cuenta_orden")
        self.label_txt_cuenta_orden.setGeometry(QRect(20, 570, 91, 16))
        self.label_txt_libre = QLabel(self.centralwidget)
        self.label_txt_libre.setObjectName(u"label_txt_libre")
        self.label_txt_libre.setGeometry(QRect(20, 590, 47, 13))
        self.label_txt_codigo_catastro = QLabel(self.centralwidget)
        self.label_txt_codigo_catastro.setObjectName(u"label_txt_codigo_catastro")
        self.label_txt_codigo_catastro.setGeometry(QRect(20, 610, 111, 16))
        self.label_txt_codigo_rentas = QLabel(self.centralwidget)
        self.label_txt_codigo_rentas.setObjectName(u"label_txt_codigo_rentas")
        self.label_txt_codigo_rentas.setGeometry(QRect(20, 630, 91, 16))
        self.label_txt_codigo_aguas_cordobesas = QLabel(self.centralwidget)
        self.label_txt_codigo_aguas_cordobesas.setObjectName(u"label_txt_codigo_aguas_cordobesas")
        self.label_txt_codigo_aguas_cordobesas.setGeometry(QRect(20, 650, 151, 16))
        self.label_txt_conceptos_incluidos = QLabel(self.centralwidget)
        self.label_txt_conceptos_incluidos.setObjectName(u"label_txt_conceptos_incluidos")
        self.label_txt_conceptos_incluidos.setGeometry(QRect(20, 670, 111, 16))
        self.label_txt_paga_por_transferencia = QLabel(self.centralwidget)
        self.label_txt_paga_por_transferencia.setObjectName(u"label_txt_paga_por_transferencia")
        self.label_txt_paga_por_transferencia.setGeometry(QRect(20, 690, 121, 16))
        self.label_domicilio = QLabel(self.centralwidget)
        self.label_domicilio.setObjectName(u"label_domicilio")
        self.label_domicilio.setGeometry(QRect(110, 110, 281, 16))
        self.label_numero_de_telefono = QLabel(self.centralwidget)
        self.label_numero_de_telefono.setObjectName(u"label_numero_de_telefono")
        self.label_numero_de_telefono.setGeometry(QRect(130, 130, 251, 16))
        self.label_monto_de_alquiler = QLabel(self.centralwidget)
        self.label_monto_de_alquiler.setObjectName(u"label_monto_de_alquiler")
        self.label_monto_de_alquiler.setGeometry(QRect(110, 150, 281, 16))
        self.label_monto_deposito_numero = QLabel(self.centralwidget)
        self.label_monto_deposito_numero.setObjectName(u"label_monto_deposito_numero")
        self.label_monto_deposito_numero.setGeometry(QRect(150, 170, 251, 21))
        self.dateEdit = QDateEdit(self.centralwidget)
        self.dateEdit.setObjectName(u"dateEdit")
        self.dateEdit.setGeometry(QRect(160, 190, 110, 16))
        self.dateEdit.setReadOnly(True)
        self.dateEdit_2 = QDateEdit(self.centralwidget)
        self.dateEdit_2.setObjectName(u"dateEdit_2")
        self.dateEdit_2.setGeometry(QRect(150, 210, 110, 16))
        self.dateEdit_2.setReadOnly(True)
        self.label_nombre_propietario = QLabel(self.centralwidget)
        self.label_nombre_propietario.setObjectName(u"label_nombre_propietario")
        self.label_nombre_propietario.setGeometry(QRect(80, 230, 311, 16))
        self.label_tipo_de_comision = QLabel(self.centralwidget)
        self.label_tipo_de_comision.setObjectName(u"label_tipo_de_comision")
        self.label_tipo_de_comision.setGeometry(QRect(110, 250, 281, 16))
        self.label_monto_de_comision = QLabel(self.centralwidget)
        self.label_monto_de_comision.setObjectName(u"label_monto_de_comision")
        self.label_monto_de_comision.setGeometry(QRect(120, 270, 271, 16))
        self.label_cuota_aguas_cordobesas = QLabel(self.centralwidget)
        self.label_cuota_aguas_cordobesas.setObjectName(u"label_cuota_aguas_cordobesas")
        self.label_cuota_aguas_cordobesas.setGeometry(QRect(170, 290, 221, 16))
        self.label_importe_aguas_cordobesas = QLabel(self.centralwidget)
        self.label_importe_aguas_cordobesas.setObjectName(u"label_importe_aguas_cordobesas")
        self.label_importe_aguas_cordobesas.setGeometry(QRect(180, 310, 211, 16))
        self.label_porcentual_aguas_cordobesas = QLabel(self.centralwidget)
        self.label_porcentual_aguas_cordobesas.setObjectName(u"label_porcentual_aguas_cordobesas")
        self.label_porcentual_aguas_cordobesas.setGeometry(QRect(220, 330, 171, 16))
        self.label_quien_paga_aguas = QLabel(self.centralwidget)
        self.label_quien_paga_aguas.setObjectName(u"label_quien_paga_aguas")
        self.label_quien_paga_aguas.setGeometry(QRect(150, 350, 241, 16))
        self.label_cuota_muni = QLabel(self.centralwidget)
        self.label_cuota_muni.setObjectName(u"label_cuota_muni")
        self.label_cuota_muni.setGeometry(QRect(100, 370, 291, 16))
        self.label_importe_muni = QLabel(self.centralwidget)
        self.label_importe_muni.setObjectName(u"label_importe_muni")
        self.label_importe_muni.setGeometry(QRect(110, 390, 281, 16))
        self.label_quien_paga_muni = QLabel(self.centralwidget)
        self.label_quien_paga_muni.setObjectName(u"label_quien_paga_muni")
        self.label_quien_paga_muni.setGeometry(QRect(110, 410, 281, 16))
        self.label_cuota_rentas = QLabel(self.centralwidget)
        self.label_cuota_rentas.setObjectName(u"label_cuota_rentas")
        self.label_cuota_rentas.setGeometry(QRect(110, 430, 281, 16))
        self.label_importe_rentas = QLabel(self.centralwidget)
        self.label_importe_rentas.setObjectName(u"label_importe_rentas")
        self.label_importe_rentas.setGeometry(QRect(120, 450, 271, 16))
        self.label_quien_paga_rentas = QLabel(self.centralwidget)
        self.label_quien_paga_rentas.setObjectName(u"label_quien_paga_rentas")
        self.label_quien_paga_rentas.setGeometry(QRect(120, 470, 271, 16))
        self.label_monto_unico = QLabel(self.centralwidget)
        self.label_monto_unico.setObjectName(u"label_monto_unico")
        self.label_monto_unico.setGeometry(QRect(90, 490, 301, 16))
        self.label_mes_expensa = QLabel(self.centralwidget)
        self.label_mes_expensa.setObjectName(u"label_mes_expensa")
        self.label_mes_expensa.setGeometry(QRect(90, 510, 301, 16))
        self.label_monto_expensa = QLabel(self.centralwidget)
        self.label_monto_expensa.setObjectName(u"label_monto_expensa")
        self.label_monto_expensa.setGeometry(QRect(100, 530, 291, 16))
        self.label_adicional_pagares = QLabel(self.centralwidget)
        self.label_adicional_pagares.setObjectName(u"label_adicional_pagares")
        self.label_adicional_pagares.setGeometry(QRect(110, 550, 281, 16))
        self.label_cuenta_orden = QLabel(self.centralwidget)
        self.label_cuenta_orden.setObjectName(u"label_cuenta_orden")
        self.label_cuenta_orden.setGeometry(QRect(110, 570, 281, 16))
        self.label_libre = QLabel(self.centralwidget)
        self.label_libre.setObjectName(u"label_libre")
        self.label_libre.setGeometry(QRect(50, 590, 47, 13))
        self.label_codigo_catastro = QLabel(self.centralwidget)
        self.label_codigo_catastro.setObjectName(u"label_codigo_catastro")
        self.label_codigo_catastro.setGeometry(QRect(120, 610, 271, 16))
        self.label_codigo_rentas = QLabel(self.centralwidget)
        self.label_codigo_rentas.setObjectName(u"label_codigo_rentas")
        self.label_codigo_rentas.setGeometry(QRect(120, 630, 281, 16))
        self.label_codigo_aguas_cordobesas = QLabel(self.centralwidget)
        self.label_codigo_aguas_cordobesas.setObjectName(u"label_codigo_aguas_cordobesas")
        self.label_codigo_aguas_cordobesas.setGeometry(QRect(170, 650, 221, 16))
        self.label_conceptos_incluidos = QLabel(self.centralwidget)
        self.label_conceptos_incluidos.setObjectName(u"label_conceptos_incluidos")
        self.label_conceptos_incluidos.setGeometry(QRect(130, 670, 271, 16))
        self.label_paga_por_transferencia = QLabel(self.centralwidget)
        self.label_paga_por_transferencia.setObjectName(u"label_paga_por_transferencia")
        self.label_paga_por_transferencia.setGeometry(QRect(140, 690, 251, 16))
        self.btn_actualizar_aguas_cordobesas = QPushButton(self.centralwidget)
        self.btn_actualizar_aguas_cordobesas.setObjectName(u"btn_actualizar_aguas_cordobesas")
        self.btn_actualizar_aguas_cordobesas.setGeometry(QRect(20, 720, 151, 31))
        self.btn_exit = QPushButton(self.centralwidget)
        self.btn_exit.setObjectName(u"btn_exit")
        self.btn_exit.setGeometry(QRect(320, 720, 75, 31))
        self.btn_exit.setStyleSheet(u"background-color: red;\n"
"color: white;\n"
"font: 75 10pt \"Arial\";")
        self.le_periodo_a_buscar = QLineEdit(self.centralwidget)
        self.le_periodo_a_buscar.setObjectName(u"le_periodo_a_buscar")
        self.le_periodo_a_buscar.setGeometry(QRect(20, 760, 151, 20))
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.cb_seleccionar_cliente.setItemText(0, QCoreApplication.translate("MainWindow", u"Sin Selecci\u00f3n", None))

        self.label_txt_seleccione_cliente.setText(QCoreApplication.translate("MainWindow", u"Seleccione el cliente:", None))
        self.label_txt_id.setText(QCoreApplication.translate("MainWindow", u"ID:", None))
        self.label_id_cliente.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_txt_domicilio_alquiler.setText(QCoreApplication.translate("MainWindow", u"Domicilio Alquiler:", None))
        self.label_txt_numero_telefono.setText(QCoreApplication.translate("MainWindow", u"N\u00famero de Tel\u00e9fono:", None))
        self.label_txt_monto_alquiler.setText(QCoreApplication.translate("MainWindow", u"Monto de Alquiler:", None))
        self.label_txt_monto_deposito_numero.setText(QCoreApplication.translate("MainWindow", u"Monto Dep\u00f3sito N\u00famero:", None))
        self.label_txt_fecha_inicio_contrato.setText(QCoreApplication.translate("MainWindow", u"Fecha de Inicio del Contrato:", None))
        self.label_txt_fecha_fin_contrato.setText(QCoreApplication.translate("MainWindow", u"Fecha de Fin del Contrato:", None))
        self.label_txt_propietario.setText(QCoreApplication.translate("MainWindow", u"Propietario:", None))
        self.label_txt_tipo_comision.setText(QCoreApplication.translate("MainWindow", u"Tipo de Comisi\u00f3n:", None))
        self.label_txt_monto_comision.setText(QCoreApplication.translate("MainWindow", u"Monto de Comisi\u00f3n:", None))
        self.label_txt_cuota_aguas_cordobesas.setText(QCoreApplication.translate("MainWindow", u"Cuota de Aguas Cordobesas:", None))
        self.label_txt_importe_aguas_cordobesas.setText(QCoreApplication.translate("MainWindow", u"Importe de Aguas Cordobesas:", None))
        self.label_txt_porcentual_aguas_cordobesas.setText(QCoreApplication.translate("MainWindow", u"Porcentual de Aguas Cordobesas e Imp.:", None))
        self.label_txt_quien_paga_aguas.setText(QCoreApplication.translate("MainWindow", u"Qui\u00e9n Paga Aguas e Imp.:", None))
        self.label_txt_cuota_muni.setText(QCoreApplication.translate("MainWindow", u"Cuota de Muni:", None))
        self.label_txt_importe_muni.setText(QCoreApplication.translate("MainWindow", u"Importe de Muni:", None))
        self.label_txt_quien_paga_muni.setText(QCoreApplication.translate("MainWindow", u"Qui\u00e9n Paga Muni:", None))
        self.label_txt_cuota_rentas.setText(QCoreApplication.translate("MainWindow", u"Cuota de Rentas:", None))
        self.label_txt_importe_rentas.setText(QCoreApplication.translate("MainWindow", u"Importe de Rentas:", None))
        self.label_txt_quien_paga_rentas.setText(QCoreApplication.translate("MainWindow", u"Qui\u00e9n Paga Rentas:", None))
        self.label_txt_monto_unico.setText(QCoreApplication.translate("MainWindow", u"Monto \u00danico:", None))
        self.label_txt_mes_expensa.setText(QCoreApplication.translate("MainWindow", u"Mes Expensa:", None))
        self.label_txt_monto_expensa.setText(QCoreApplication.translate("MainWindow", u"Monto Expensa:", None))
        self.label_txt_adicional_pagares.setText(QCoreApplication.translate("MainWindow", u"Adicional Pagar\u00e9s:", None))
        self.label_txt_cuenta_orden.setText(QCoreApplication.translate("MainWindow", u"Cuenta y Orden:", None))
        self.label_txt_libre.setText(QCoreApplication.translate("MainWindow", u"Libre:", None))
        self.label_txt_codigo_catastro.setText(QCoreApplication.translate("MainWindow", u"C\u00f3digo de Catastro:", None))
        self.label_txt_codigo_rentas.setText(QCoreApplication.translate("MainWindow", u"C\u00f3digo de Rentas:", None))
        self.label_txt_codigo_aguas_cordobesas.setText(QCoreApplication.translate("MainWindow", u"C\u00f3digo de Aguas Cordobesas:", None))
        self.label_txt_conceptos_incluidos.setText(QCoreApplication.translate("MainWindow", u"Conceptos Incluidos:", None))
        self.label_txt_paga_por_transferencia.setText(QCoreApplication.translate("MainWindow", u"Paga por Transferencia:", None))
        self.label_domicilio.setText(QCoreApplication.translate("MainWindow", u"\"Domicilio\"", None))
        self.label_numero_de_telefono.setText(QCoreApplication.translate("MainWindow", u"000000000", None))
        self.label_monto_de_alquiler.setText(QCoreApplication.translate("MainWindow", u"$ 0", None))
        self.label_monto_deposito_numero.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_nombre_propietario.setText(QCoreApplication.translate("MainWindow", u"\"Nombre\"", None))
        self.label_tipo_de_comision.setText(QCoreApplication.translate("MainWindow", u"Porcentaje", None))
        self.label_monto_de_comision.setText(QCoreApplication.translate("MainWindow", u"0 %", None))
        self.label_cuota_aguas_cordobesas.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_importe_aguas_cordobesas.setText(QCoreApplication.translate("MainWindow", u"$ 0", None))
        self.label_porcentual_aguas_cordobesas.setText(QCoreApplication.translate("MainWindow", u"0 %", None))
        self.label_quien_paga_aguas.setText(QCoreApplication.translate("MainWindow", u"Inquilino", None))
        self.label_cuota_muni.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_importe_muni.setText(QCoreApplication.translate("MainWindow", u"$ 0", None))
        self.label_quien_paga_muni.setText(QCoreApplication.translate("MainWindow", u"Inquilino", None))
        self.label_cuota_rentas.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_importe_rentas.setText(QCoreApplication.translate("MainWindow", u"$ 0", None))
        self.label_quien_paga_rentas.setText(QCoreApplication.translate("MainWindow", u"Inquilino", None))
        self.label_monto_unico.setText(QCoreApplication.translate("MainWindow", u"$ 0", None))
        self.label_mes_expensa.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_monto_expensa.setText(QCoreApplication.translate("MainWindow", u"$ 0", None))
        self.label_adicional_pagares.setText(QCoreApplication.translate("MainWindow", u"$ 0", None))
        self.label_cuenta_orden.setText(QCoreApplication.translate("MainWindow", u"No", None))
        self.label_libre.setText(QCoreApplication.translate("MainWindow", u"\"Libre\"", None))
        self.label_codigo_catastro.setText(QCoreApplication.translate("MainWindow", u"000000000000000", None))
        self.label_codigo_rentas.setText(QCoreApplication.translate("MainWindow", u"000000000000", None))
        self.label_codigo_aguas_cordobesas.setText(QCoreApplication.translate("MainWindow", u"000000", None))
        self.label_conceptos_incluidos.setText(QCoreApplication.translate("MainWindow", u"\"Conceptos\"", None))
        self.label_paga_por_transferencia.setText(QCoreApplication.translate("MainWindow", u"No", None))
        self.btn_actualizar_aguas_cordobesas.setText(QCoreApplication.translate("MainWindow", u"Actualizar Aguas Cordobesas", None))
        self.btn_exit.setText(QCoreApplication.translate("MainWindow", u"Salir", None))
        self.le_periodo_a_buscar.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Periodo a Buscar", None))
    # retranslateUi

