# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'editar_clientes.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        if not Dialog.objectName():
            Dialog.setObjectName(u"Dialog")
        Dialog.resize(389, 845)
        self.label = QLabel(Dialog)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 10, 101, 16))
        font = QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.cb_seleccionar_cliente = QComboBox(Dialog)
        self.cb_seleccionar_cliente.addItem("")
        self.cb_seleccionar_cliente.setObjectName(u"cb_seleccionar_cliente")
        self.cb_seleccionar_cliente.setGeometry(QRect(10, 50, 371, 22))
        self.label_txt_seleccione_cliente = QLabel(Dialog)
        self.label_txt_seleccione_cliente.setObjectName(u"label_txt_seleccione_cliente")
        self.label_txt_seleccione_cliente.setGeometry(QRect(10, 30, 131, 16))
        self.label_txt_paga_por_transferencia = QLabel(Dialog)
        self.label_txt_paga_por_transferencia.setObjectName(u"label_txt_paga_por_transferencia")
        self.label_txt_paga_por_transferencia.setGeometry(QRect(10, 720, 121, 16))
        self.label_txt_importe_aguas_cordobesas = QLabel(Dialog)
        self.label_txt_importe_aguas_cordobesas.setObjectName(u"label_txt_importe_aguas_cordobesas")
        self.label_txt_importe_aguas_cordobesas.setGeometry(QRect(10, 340, 161, 16))
        self.label_txt_cuenta_orden = QLabel(Dialog)
        self.label_txt_cuenta_orden.setObjectName(u"label_txt_cuenta_orden")
        self.label_txt_cuenta_orden.setGeometry(QRect(10, 600, 91, 16))
        self.label_txt_quien_paga_rentas = QLabel(Dialog)
        self.label_txt_quien_paga_rentas.setObjectName(u"label_txt_quien_paga_rentas")
        self.label_txt_quien_paga_rentas.setGeometry(QRect(10, 500, 101, 16))
        self.label_txt_fecha_fin_contrato = QLabel(Dialog)
        self.label_txt_fecha_fin_contrato.setObjectName(u"label_txt_fecha_fin_contrato")
        self.label_txt_fecha_fin_contrato.setGeometry(QRect(10, 240, 131, 16))
        self.label_txt_cuota_aguas_cordobesas = QLabel(Dialog)
        self.label_txt_cuota_aguas_cordobesas.setObjectName(u"label_txt_cuota_aguas_cordobesas")
        self.label_txt_cuota_aguas_cordobesas.setGeometry(QRect(10, 320, 151, 16))
        self.label_txt_quien_paga_aguas = QLabel(Dialog)
        self.label_txt_quien_paga_aguas.setObjectName(u"label_txt_quien_paga_aguas")
        self.label_txt_quien_paga_aguas.setGeometry(QRect(10, 380, 131, 16))
        self.label_txt_codigo_catastro = QLabel(Dialog)
        self.label_txt_codigo_catastro.setObjectName(u"label_txt_codigo_catastro")
        self.label_txt_codigo_catastro.setGeometry(QRect(10, 640, 111, 16))
        self.label_txt_id = QLabel(Dialog)
        self.label_txt_id.setObjectName(u"label_txt_id")
        self.label_txt_id.setGeometry(QRect(10, 120, 47, 13))
        self.label_txt_codigo_aguas_cordobesas = QLabel(Dialog)
        self.label_txt_codigo_aguas_cordobesas.setObjectName(u"label_txt_codigo_aguas_cordobesas")
        self.label_txt_codigo_aguas_cordobesas.setGeometry(QRect(10, 680, 151, 16))
        self.label_txt_porcentual_aguas_cordobesas = QLabel(Dialog)
        self.label_txt_porcentual_aguas_cordobesas.setObjectName(u"label_txt_porcentual_aguas_cordobesas")
        self.label_txt_porcentual_aguas_cordobesas.setGeometry(QRect(10, 360, 201, 16))
        self.label_txt_tipo_comision = QLabel(Dialog)
        self.label_txt_tipo_comision.setObjectName(u"label_txt_tipo_comision")
        self.label_txt_tipo_comision.setGeometry(QRect(10, 280, 91, 16))
        self.label_txt_monto_expensa = QLabel(Dialog)
        self.label_txt_monto_expensa.setObjectName(u"label_txt_monto_expensa")
        self.label_txt_monto_expensa.setGeometry(QRect(10, 560, 81, 16))
        self.label_txt_domicilio_alquiler = QLabel(Dialog)
        self.label_txt_domicilio_alquiler.setObjectName(u"label_txt_domicilio_alquiler")
        self.label_txt_domicilio_alquiler.setGeometry(QRect(10, 140, 81, 16))
        self.label_txt_cuota_rentas = QLabel(Dialog)
        self.label_txt_cuota_rentas.setObjectName(u"label_txt_cuota_rentas")
        self.label_txt_cuota_rentas.setGeometry(QRect(10, 460, 91, 16))
        self.label_txt_quien_paga_muni = QLabel(Dialog)
        self.label_txt_quien_paga_muni.setObjectName(u"label_txt_quien_paga_muni")
        self.label_txt_quien_paga_muni.setGeometry(QRect(10, 440, 91, 16))
        self.label_txt_importe_muni = QLabel(Dialog)
        self.label_txt_importe_muni.setObjectName(u"label_txt_importe_muni")
        self.label_txt_importe_muni.setGeometry(QRect(10, 420, 91, 16))
        self.label_txt_codigo_rentas = QLabel(Dialog)
        self.label_txt_codigo_rentas.setObjectName(u"label_txt_codigo_rentas")
        self.label_txt_codigo_rentas.setGeometry(QRect(10, 660, 91, 16))
        self.label_txt_monto_comision = QLabel(Dialog)
        self.label_txt_monto_comision.setObjectName(u"label_txt_monto_comision")
        self.label_txt_monto_comision.setGeometry(QRect(10, 300, 101, 16))
        self.label_txt_monto_alquiler = QLabel(Dialog)
        self.label_txt_monto_alquiler.setObjectName(u"label_txt_monto_alquiler")
        self.label_txt_monto_alquiler.setGeometry(QRect(10, 180, 91, 16))
        self.label_txt_monto_unico = QLabel(Dialog)
        self.label_txt_monto_unico.setObjectName(u"label_txt_monto_unico")
        self.label_txt_monto_unico.setGeometry(QRect(10, 520, 71, 16))
        self.label_txt_conceptos_incluidos = QLabel(Dialog)
        self.label_txt_conceptos_incluidos.setObjectName(u"label_txt_conceptos_incluidos")
        self.label_txt_conceptos_incluidos.setGeometry(QRect(10, 700, 111, 16))
        self.label_txt_adicional_pagares = QLabel(Dialog)
        self.label_txt_adicional_pagares.setObjectName(u"label_txt_adicional_pagares")
        self.label_txt_adicional_pagares.setGeometry(QRect(10, 580, 91, 16))
        self.label_txt_monto_deposito_numero = QLabel(Dialog)
        self.label_txt_monto_deposito_numero.setObjectName(u"label_txt_monto_deposito_numero")
        self.label_txt_monto_deposito_numero.setGeometry(QRect(10, 200, 121, 20))
        self.label_txt_importe_rentas = QLabel(Dialog)
        self.label_txt_importe_rentas.setObjectName(u"label_txt_importe_rentas")
        self.label_txt_importe_rentas.setGeometry(QRect(10, 480, 111, 16))
        self.label_txt_fecha_inicio_contrato = QLabel(Dialog)
        self.label_txt_fecha_inicio_contrato.setObjectName(u"label_txt_fecha_inicio_contrato")
        self.label_txt_fecha_inicio_contrato.setGeometry(QRect(10, 220, 151, 16))
        self.label_txt_mes_expensa = QLabel(Dialog)
        self.label_txt_mes_expensa.setObjectName(u"label_txt_mes_expensa")
        self.label_txt_mes_expensa.setGeometry(QRect(10, 540, 71, 16))
        self.label_txt_propietario = QLabel(Dialog)
        self.label_txt_propietario.setObjectName(u"label_txt_propietario")
        self.label_txt_propietario.setGeometry(QRect(10, 260, 71, 16))
        self.label_txt_libre = QLabel(Dialog)
        self.label_txt_libre.setObjectName(u"label_txt_libre")
        self.label_txt_libre.setGeometry(QRect(10, 620, 47, 13))
        self.label_txt_cuota_muni = QLabel(Dialog)
        self.label_txt_cuota_muni.setObjectName(u"label_txt_cuota_muni")
        self.label_txt_cuota_muni.setGeometry(QRect(10, 400, 81, 16))
        self.label_txt_numero_telefono = QLabel(Dialog)
        self.label_txt_numero_telefono.setObjectName(u"label_txt_numero_telefono")
        self.label_txt_numero_telefono.setGeometry(QRect(10, 160, 101, 16))
        self.le_id = QLineEdit(Dialog)
        self.le_id.setObjectName(u"le_id")
        self.le_id.setGeometry(QRect(30, 120, 351, 16))
        self.le_domicilio_alquiler = QLineEdit(Dialog)
        self.le_domicilio_alquiler.setObjectName(u"le_domicilio_alquiler")
        self.le_domicilio_alquiler.setGeometry(QRect(100, 140, 281, 16))
        self.le_numero_telefono = QLineEdit(Dialog)
        self.le_numero_telefono.setObjectName(u"le_numero_telefono")
        self.le_numero_telefono.setGeometry(QRect(120, 160, 261, 16))
        self.le_monto_alquiler = QLineEdit(Dialog)
        self.le_monto_alquiler.setObjectName(u"le_monto_alquiler")
        self.le_monto_alquiler.setGeometry(QRect(100, 180, 281, 16))
        self.le_monto_deposito_numero = QLineEdit(Dialog)
        self.le_monto_deposito_numero.setObjectName(u"le_monto_deposito_numero")
        self.le_monto_deposito_numero.setGeometry(QRect(130, 200, 251, 16))
        self.le_propietario = QLineEdit(Dialog)
        self.le_propietario.setObjectName(u"le_propietario")
        self.le_propietario.setGeometry(QRect(70, 260, 311, 16))
        self.le_tipo_comision = QLineEdit(Dialog)
        self.le_tipo_comision.setObjectName(u"le_tipo_comision")
        self.le_tipo_comision.setGeometry(QRect(100, 280, 281, 16))
        self.le_monto_comision = QLineEdit(Dialog)
        self.le_monto_comision.setObjectName(u"le_monto_comision")
        self.le_monto_comision.setGeometry(QRect(110, 300, 271, 16))
        self.le_cuota_aguas = QLineEdit(Dialog)
        self.le_cuota_aguas.setObjectName(u"le_cuota_aguas")
        self.le_cuota_aguas.setGeometry(QRect(160, 320, 221, 16))
        self.le_importe_aguas = QLineEdit(Dialog)
        self.le_importe_aguas.setObjectName(u"le_importe_aguas")
        self.le_importe_aguas.setGeometry(QRect(170, 340, 211, 16))
        self.le_porcentual_aguas = QLineEdit(Dialog)
        self.le_porcentual_aguas.setObjectName(u"le_porcentual_aguas")
        self.le_porcentual_aguas.setGeometry(QRect(210, 360, 171, 16))
        self.le_quien_paga_aguas = QLineEdit(Dialog)
        self.le_quien_paga_aguas.setObjectName(u"le_quien_paga_aguas")
        self.le_quien_paga_aguas.setGeometry(QRect(140, 380, 241, 16))
        self.le_cuota_de_muni = QLineEdit(Dialog)
        self.le_cuota_de_muni.setObjectName(u"le_cuota_de_muni")
        self.le_cuota_de_muni.setGeometry(QRect(90, 400, 291, 16))
        self.le_importe_muni = QLineEdit(Dialog)
        self.le_importe_muni.setObjectName(u"le_importe_muni")
        self.le_importe_muni.setGeometry(QRect(100, 420, 281, 16))
        self.le_quien_paga_muni = QLineEdit(Dialog)
        self.le_quien_paga_muni.setObjectName(u"le_quien_paga_muni")
        self.le_quien_paga_muni.setGeometry(QRect(100, 440, 281, 16))
        self.le_cuota_rentas = QLineEdit(Dialog)
        self.le_cuota_rentas.setObjectName(u"le_cuota_rentas")
        self.le_cuota_rentas.setGeometry(QRect(100, 460, 281, 16))
        self.le_importe_rentas = QLineEdit(Dialog)
        self.le_importe_rentas.setObjectName(u"le_importe_rentas")
        self.le_importe_rentas.setGeometry(QRect(110, 480, 271, 16))
        self.le_quien_paga_rentas = QLineEdit(Dialog)
        self.le_quien_paga_rentas.setObjectName(u"le_quien_paga_rentas")
        self.le_quien_paga_rentas.setGeometry(QRect(110, 500, 271, 16))
        self.le_monto_unico = QLineEdit(Dialog)
        self.le_monto_unico.setObjectName(u"le_monto_unico")
        self.le_monto_unico.setGeometry(QRect(80, 520, 301, 16))
        self.le_mes_expensa = QLineEdit(Dialog)
        self.le_mes_expensa.setObjectName(u"le_mes_expensa")
        self.le_mes_expensa.setGeometry(QRect(80, 540, 301, 16))
        self.le_monto_expensa = QLineEdit(Dialog)
        self.le_monto_expensa.setObjectName(u"le_monto_expensa")
        self.le_monto_expensa.setGeometry(QRect(90, 560, 291, 16))
        self.le_adicional_pagares = QLineEdit(Dialog)
        self.le_adicional_pagares.setObjectName(u"le_adicional_pagares")
        self.le_adicional_pagares.setGeometry(QRect(100, 580, 281, 16))
        self.le_libre = QLineEdit(Dialog)
        self.le_libre.setObjectName(u"le_libre")
        self.le_libre.setGeometry(QRect(40, 620, 341, 16))
        self.le_codigo_catastro = QLineEdit(Dialog)
        self.le_codigo_catastro.setObjectName(u"le_codigo_catastro")
        self.le_codigo_catastro.setGeometry(QRect(110, 640, 271, 16))
        self.le_codigo_rentas = QLineEdit(Dialog)
        self.le_codigo_rentas.setObjectName(u"le_codigo_rentas")
        self.le_codigo_rentas.setGeometry(QRect(100, 660, 281, 16))
        self.le_codigo_aguas = QLineEdit(Dialog)
        self.le_codigo_aguas.setObjectName(u"le_codigo_aguas")
        self.le_codigo_aguas.setGeometry(QRect(160, 680, 221, 16))
        self.le_conceptos_incluidos = QLineEdit(Dialog)
        self.le_conceptos_incluidos.setObjectName(u"le_conceptos_incluidos")
        self.le_conceptos_incluidos.setGeometry(QRect(110, 700, 271, 16))
        self.de_inicio_contrato = QDateEdit(Dialog)
        self.de_inicio_contrato.setObjectName(u"de_inicio_contrato")
        self.de_inicio_contrato.setGeometry(QRect(150, 220, 231, 16))
        self.de_final_contrato = QDateEdit(Dialog)
        self.de_final_contrato.setObjectName(u"de_final_contrato")
        self.de_final_contrato.setGeometry(QRect(150, 240, 231, 16))
        self.btn_aplicar = QPushButton(Dialog)
        self.btn_aplicar.setObjectName(u"btn_aplicar")
        self.btn_aplicar.setGeometry(QRect(10, 780, 131, 23))
        self.btn_volver = QPushButton(Dialog)
        self.btn_volver.setObjectName(u"btn_volver")
        self.btn_volver.setGeometry(QRect(250, 780, 131, 23))
        self.btn_aplicar_volver = QPushButton(Dialog)
        self.btn_aplicar_volver.setObjectName(u"btn_aplicar_volver")
        self.btn_aplicar_volver.setGeometry(QRect(10, 810, 131, 23))
        self.btn_exit = QPushButton(Dialog)
        self.btn_exit.setObjectName(u"btn_exit")
        self.btn_exit.setGeometry(QRect(310, 810, 75, 31))
        self.btn_exit.setStyleSheet(u"background-color: red;\n"
"color: white;\n"
"font: 75 10pt \"Arial\";")
        self.checkBox = QCheckBox(Dialog)
        self.checkBox.setObjectName(u"checkBox")
        self.checkBox.setGeometry(QRect(130, 720, 70, 17))
        self.checkBox_2 = QCheckBox(Dialog)
        self.checkBox_2.setObjectName(u"checkBox_2")
        self.checkBox_2.setGeometry(QRect(100, 600, 70, 17))
        self.checkBox_2.setChecked(False)
        self.le_url_aguas = QLineEdit(Dialog)
        self.le_url_aguas.setObjectName(u"le_url_aguas")
        self.le_url_aguas.setGeometry(QRect(150, 740, 231, 16))
        self.label_txt_url_aguas_cordobesas = QLabel(Dialog)
        self.label_txt_url_aguas_cordobesas.setObjectName(u"label_txt_url_aguas_cordobesas")
        self.label_txt_url_aguas_cordobesas.setGeometry(QRect(10, 740, 151, 16))

        self.retranslateUi(Dialog)

        QMetaObject.connectSlotsByName(Dialog)
    # setupUi

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QCoreApplication.translate("Dialog", u"Dialog", None))
        self.label.setText(QCoreApplication.translate("Dialog", u"EDITAR CLIENTES", None))
        self.cb_seleccionar_cliente.setItemText(0, QCoreApplication.translate("Dialog", u"Sin Selecci\u00f3n", None))

        self.label_txt_seleccione_cliente.setText(QCoreApplication.translate("Dialog", u"Seleccione el cliente:", None))
        self.label_txt_paga_por_transferencia.setText(QCoreApplication.translate("Dialog", u"Paga por Transferencia:", None))
        self.label_txt_importe_aguas_cordobesas.setText(QCoreApplication.translate("Dialog", u"Importe de Aguas Cordobesas:", None))
        self.label_txt_cuenta_orden.setText(QCoreApplication.translate("Dialog", u"Cuenta y Orden:", None))
        self.label_txt_quien_paga_rentas.setText(QCoreApplication.translate("Dialog", u"Qui\u00e9n Paga Rentas:", None))
        self.label_txt_fecha_fin_contrato.setText(QCoreApplication.translate("Dialog", u"Fecha de Fin del Contrato:", None))
        self.label_txt_cuota_aguas_cordobesas.setText(QCoreApplication.translate("Dialog", u"Cuota de Aguas Cordobesas:", None))
        self.label_txt_quien_paga_aguas.setText(QCoreApplication.translate("Dialog", u"Qui\u00e9n Paga Aguas e Imp.:", None))
        self.label_txt_codigo_catastro.setText(QCoreApplication.translate("Dialog", u"C\u00f3digo de Catastro:", None))
        self.label_txt_id.setText(QCoreApplication.translate("Dialog", u"ID:", None))
        self.label_txt_codigo_aguas_cordobesas.setText(QCoreApplication.translate("Dialog", u"C\u00f3digo de Aguas Cordobesas:", None))
        self.label_txt_porcentual_aguas_cordobesas.setText(QCoreApplication.translate("Dialog", u"Porcentual de Aguas Cordobesas e Imp.:", None))
        self.label_txt_tipo_comision.setText(QCoreApplication.translate("Dialog", u"Tipo de Comisi\u00f3n:", None))
        self.label_txt_monto_expensa.setText(QCoreApplication.translate("Dialog", u"Monto Expensa:", None))
        self.label_txt_domicilio_alquiler.setText(QCoreApplication.translate("Dialog", u"Domicilio Alquiler:", None))
        self.label_txt_cuota_rentas.setText(QCoreApplication.translate("Dialog", u"Cuota de Rentas:", None))
        self.label_txt_quien_paga_muni.setText(QCoreApplication.translate("Dialog", u"Qui\u00e9n Paga Muni:", None))
        self.label_txt_importe_muni.setText(QCoreApplication.translate("Dialog", u"Importe de Muni:", None))
        self.label_txt_codigo_rentas.setText(QCoreApplication.translate("Dialog", u"C\u00f3digo de Rentas:", None))
        self.label_txt_monto_comision.setText(QCoreApplication.translate("Dialog", u"Monto de Comisi\u00f3n:", None))
        self.label_txt_monto_alquiler.setText(QCoreApplication.translate("Dialog", u"Monto de Alquiler:", None))
        self.label_txt_monto_unico.setText(QCoreApplication.translate("Dialog", u"Monto \u00danico:", None))
        self.label_txt_conceptos_incluidos.setText(QCoreApplication.translate("Dialog", u"Conceptos Incluidos:", None))
        self.label_txt_adicional_pagares.setText(QCoreApplication.translate("Dialog", u"Adicional Pagar\u00e9s:", None))
        self.label_txt_monto_deposito_numero.setText(QCoreApplication.translate("Dialog", u"Monto Dep\u00f3sito N\u00famero:", None))
        self.label_txt_importe_rentas.setText(QCoreApplication.translate("Dialog", u"Importe de Rentas:", None))
        self.label_txt_fecha_inicio_contrato.setText(QCoreApplication.translate("Dialog", u"Fecha de Inicio del Contrato:", None))
        self.label_txt_mes_expensa.setText(QCoreApplication.translate("Dialog", u"Mes Expensa:", None))
        self.label_txt_propietario.setText(QCoreApplication.translate("Dialog", u"Propietario:", None))
        self.label_txt_libre.setText(QCoreApplication.translate("Dialog", u"Libre:", None))
        self.label_txt_cuota_muni.setText(QCoreApplication.translate("Dialog", u"Cuota de Muni:", None))
        self.label_txt_numero_telefono.setText(QCoreApplication.translate("Dialog", u"N\u00famero de Tel\u00e9fono:", None))
        self.btn_aplicar.setText(QCoreApplication.translate("Dialog", u"Aplicar Cambios", None))
        self.btn_volver.setText(QCoreApplication.translate("Dialog", u"Volver", None))
        self.btn_aplicar_volver.setText(QCoreApplication.translate("Dialog", u"Aplicar Cambios y Volver", None))
        self.btn_exit.setText(QCoreApplication.translate("Dialog", u"Salir", None))
        self.checkBox.setText("")
        self.checkBox_2.setText("")
        self.label_txt_url_aguas_cordobesas.setText(QCoreApplication.translate("Dialog", u"URL de Aguas Cordobesas:", None))
    # retranslateUi

